import Link from 'next/link';
import { Sparkles } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service | Manifesta',
  description: 'Terms and conditions for using Manifesta.',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-cream">
      {/* Nav */}
      <header className="border-b border-sage/10 px-6 py-4">
        <Link href="/" className="flex items-center gap-2 w-fit">
          <Sparkles className="w-4 h-4 text-gold" />
          <span className="font-display text-base font-semibold text-forest tracking-wide">Manifesta</span>
        </Link>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-16">
        <h1 className="font-display text-4xl font-semibold text-forest mb-2">Terms of Service</h1>
        <p className="font-sans text-sm text-forest/50 mb-10">Last updated: May 2025</p>

        <div className="prose prose-forest font-sans text-forest/80 space-y-8 text-sm leading-relaxed">

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Manifesta (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. You must be at least 18 years old to use Manifesta.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">2. Description of Service</h2>
            <p>
              Manifesta is an AI-powered platform that helps users create personalized vision boards, manifestation tools, daily coaching emails, and related content. The Service is provided &ldquo;as is&rdquo; and features may change over time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">3. Your Account</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You must notify us immediately at hello@joinmanifesta.com if you suspect unauthorized access to your account. We are not liable for losses arising from unauthorized account use.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">4. User Content</h2>
            <p>
              You retain ownership of any content you submit to the Service, including your dream answers, goals, and photos (&ldquo;User Content&rdquo;). By submitting User Content, you grant Manifesta a limited, non-exclusive, royalty-free license to use, store, and process your User Content solely to provide the Service.
            </p>
            <p>
              You represent and warrant that your User Content does not violate any third-party rights and does not contain illegal, harmful, or offensive material. We reserve the right to remove any User Content that violates these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">5. AI-Generated Content</h2>
            <p>
              The vision boards, manifestos, and other content generated by our AI (&ldquo;Generated Content&rdquo;) are provided for personal, non-commercial use. We do not guarantee that Generated Content will be accurate, error-free, or suitable for any particular purpose. AI outputs are probabilistic and may occasionally produce unexpected results.
            </p>
            <p>
              You may use Generated Content for your personal manifestation practice. You may not resell, redistribute, or claim Generated Content as your own original work for commercial purposes without our written consent.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">6. Photo Uploads</h2>
            <p>
              If you upload photos of yourself, you confirm that you have the right to use those photos and that they depict you or people who have consented to their use in this context. Photos are used exclusively to personalize your vision board. We do not use your photos to train AI models or share them publicly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">7. Payments and Refunds</h2>
            <p>
              The free vision board wallpaper is provided at no charge. Paid upgrades (such as the Manifesta Dream Card, guided meditations, or daily coaching) are charged at the prices listed at the time of purchase. All sales are final unless otherwise stated. If you experience a technical issue with a paid product, contact us at hello@joinmanifesta.com within 14 days for support.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">8. Prohibited Uses</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of these terms</li>
              <li>Upload content that is harmful, abusive, defamatory, or infringes third-party rights</li>
              <li>Attempt to reverse engineer, scrape, or copy the Service</li>
              <li>Use the Service to generate content that depicts real people without their consent</li>
              <li>Impersonate others or create false identities</li>
              <li>Interfere with the proper functioning of the Service</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">9. Intellectual Property</h2>
            <p>
              The Manifesta name, logo, website design, and underlying software are owned by us and protected by applicable intellectual property laws. These terms do not grant you any license to use our trademarks or branding.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">10. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT GENERATED CONTENT WILL MEET YOUR EXPECTATIONS.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">11. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, MANIFESTA AND ITS OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">12. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved exclusively in the courts located in Delaware.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">13. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. When we do, we will update the &ldquo;Last updated&rdquo; date above. Continued use of the Service after changes constitutes your acceptance of the updated Terms. If we make material changes, we will notify you by email where feasible.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-xl font-semibold text-forest">14. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:hello@joinmanifesta.com" className="text-sage underline hover:text-sage/80">
                hello@joinmanifesta.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-sage/15">
          <Link href="/" className="font-sans text-sm text-forest/50 hover:text-forest/80 transition-colors">
            ← Back to Manifesta
          </Link>
        </div>
      </main>
    </div>
  );
}
